version: "3.8"
services:
  # ------------------------------------------------------------------------------
  #           Client + Server
  # ------------------------------------------------------------------------------

  # client:
  #   container_name: client
  #   stdin_open: true
  #   build:
  #     context: client
  #     dockerfile: Dockerfile
  #   volumes:
  #     - './client/:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

  server:
    stdin_open: true
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      - GUNICORN_CMD_ARGS=--reload
    volumes:
      - ./server/:/app
      - prediction_images:/app/prediction_images
      - training_results:/app/training_results
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  # ------------------------------------------------------------------------------
  #           Prediction Microservice Workers
  # ------------------------------------------------------------------------------

  worker_example_model:
    container_name: ${PREDICTION_TEMPLATE}_worker
    command: python3 worker.py
    build:
      context: prediction
      dockerfile: Dockerfile
      args:
        - MODEL_NAME=${PREDICTION_TEMPLATE}
    volumes:
      - ./prediction/models/${PREDICTION_TEMPLATE}:/app/model
      - prediction_images:/app/images
    environment:
      - GUNICORN_CMD_ARGS=--reload
      - API_KEY=${API_KEY_PREDICTION}
      - SERVER_SOCKET=${SERVER_SOCKET}
    depends_on:
      - redis

  # ------------------------------------------------------------------------------
  #           Training Microservices
  # ------------------------------------------------------------------------------

  # mnist_fashion_dataset:
  #   stdin_open: true
  #   container_name: mnist_fashion_dataset
  #   command: uvicorn src.server.main:app --host 0.0.0.0 --port 6006 --debug --reload-dir /app --log-level debug
  #   build:
  #     context: training/MNISTFashionMicroservice
  #     dockerfile: Dockerfile
  #   environment:
  #     - GUNICORN_CMD_ARGS=--reload
  #     - DATASET_LOCATION=${MNIST_FASHION_DATASET_LOCATION}
  #     - SERVER_PORT=${SERVER_PORT}
  #     - PORT=6006
  #     - DATASET_NAME=mnist_fashion
  #   volumes:
  #     - ./training/MNISTFashionMicroservice/:/app
  #     - mnist_fashion_dataset_vol:/app/src/dataset
  #     - mnist_fashion_public_dataset_vol:/app/src/public_dataset
  #   ports:
  #     - 6006:6006

  # ------------------------------------------------------------------------------
  #           Training Microservice Workers
  # ------------------------------------------------------------------------------

  # mnist_fashion_dataset_worker:
  #   container_name: mnist_fashion_dataset_worker
  #   command: python3 src/server/worker.py
  #   build:
  #     context: training/MNISTFashionMicroservice
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./training/MNISTFashionMicroservice/:/app
  #     - mnist_fashion_dataset_vol:/app/src/dataset
  #     - mnist_fashion_public_dataset_vol:/app/src/public_dataset
  #   environment:
  #     - GUNICORN_CMD_ARGS=--reload
  #     - DATASET_NAME=mnist_fashion
  #     - SERVER_PORT=${SERVER_PORT}
  #   depends_on:
  #     - redis

  # ------------------------------------------------------------------------------
  #           Shared Dependencies
  # ------------------------------------------------------------------------------

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    command: [ "redis-server", "--port", "6379" ]
  database:
    image: mongo:latest
    container_name: database
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - db_container:/data/db

  # ------------------------------------------------------------------------------
  #           Testing
  # ------------------------------------------------------------------------------

#  testing:
#    image: python
#    container_name: testing


volumes:
  db_container:
  prediction_images:
  training_results:

  # Dataset volumes

  mnist_fashion_dataset_vol:
    name: mnist_fashion_dataset_vol
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${MNIST_FASHION_DATASET_LOCATION}
  mnist_fashion_public_dataset_vol:
    name: mnist_fashion_public_dataset_vol